---
- name: Standardizing development environment
  vars:
    home: "{{ lookup('env', 'HOME') }}"
  hosts: localhost
  pre_tasks:
    - include: tasks/common.yml
  tasks:
    - include: tasks/go.yml
    - include: tasks/docker.yml
    - include: tasks/node.yml
    - include: tasks/vue.yml
    - include: tasks/postgres.yml
    - include: tasks/firefox.yml
    - include: tasks/chrome.yml
    - include: tasks/cac.yml
    
    - include: tasks/graphics.yml
    - include: tasks/mingw.yml
    - include: tasks/blender.yml
    
    - include: tasks/terminator.yml
    - include: tasks/ble.sh.yml
    - include: tasks/micro.yml
