#!/usr/bin/env -S ansible-playbook -K
---
- name: Standardizing development environment
  vars:
    home: "{{ lookup('env', 'HOME') }}"
  hosts: localhost
  pre_tasks:
    - include_tasks: tasks/common.yml
  tasks:
    - include_tasks: tasks/python.yml
    - include_tasks: tasks/c.yml
    - include_tasks: tasks/go.yml

    - include_tasks: tasks/docker.yml

    - include_tasks: tasks/node.yml
    - include_tasks: tasks/vue.yml
    - include_tasks: tasks/postgres.yml

    - include_tasks: tasks/firefox.yml
    - include_tasks: tasks/chrome.yml
    - include_tasks: tasks/cac.yml

    - include_tasks: tasks/tilix.yml
    - include_tasks: tasks/ble.sh.yml
    - include_tasks: tasks/micro.yml
