  - name: Download Acrobat
    shell: wget -O "{{ home }}/adobe.deb" ftp://ftp.adobe.com/pub/adobe/reader/unix/9.x/9.5.5/enu/AdbeRdr9.5.5-1_i386linux_enu.deb

  - name: Setup Architecture
    become: true
    shell: dpkg --add-architecture i386

  - name: Update Apt
    become: true
    shell: apt update

  - name: Install Acrobat Dependencies
    become: true
    apt:
        name: [
            libxml2:i386,
            libcanberra-gtk-module:i386,
            gtk2-engines-murrine:i386,
            libatk-adaptor:i386
        ]

  - name: Install Acrobat
    become: true
    shell: dpkg -i "{{ home }}/adobe.deb"

# run acroread
