  - name: Install Ble Dependencies
    become: true
    apt:
        name: [
            gawk,
            lm-sensors,
            landscape-common
        ]

  - name: Clone ble.sh
    shell: git clone --recursive https://github.com/akinomyoga/ble.sh.git "{{ home }}/.config/ble.sh"

  - name: Install ble.sh
    shell: make -C "{{ home }}/.config/ble.sh" install DESTDIR="{{ home }}/.config/ble.sh" PREFIX=/usr/local

  - name: Append to bashrc
    shell: cat config/bash/.bashrc >> "{{ home }}/.bashrc"

  - name: Add ble.sh to bashrc
    shell: echo "#!/usr/bin/env bash" | cat - "{{ home }}/.bashrc" > "{{ home }}/.temp" && mv "{{ home }}/.temp" "{{ home }}/.bashrc"

  - name: Add ble.sh to bashrc
    shell: echo "[[ \$- == *i* ]] && source ~/dev/ble.sh/out/ble.sh --noattach" | cat - "{{ home }}/.bashrc" > "{{ home }}/.temp" && mv "{{ home }}/.temp" "{{ home }}/.bashrc"
