  - name: Install Ble Dependencies
    become: true
    apt:
        pkg:
        - gawk
        - lm-sensors
        - landscape-common

  - name: Clone fzf
    shell: git clone --depth 1 https://github.com/junegunn/fzf.git "{{ home }}/.config/.fzf"

  - name: Install fzf
    shell: "{{ home }}/.config/.fzf/install"

  - name: Clone ble.sh
    shell: git clone --recursive https://github.com/akinomyoga/ble.sh.git "{{ home }}/.config/ble.sh"

  - name: Install ble.sh
    shell: make -C "{{ home }}/.config/ble.sh" install DESTDIR="{{ home }}/.config/ble.sh" PREFIX=/usr/local

  - name: Append to bashrc
    shell: cat config/bash/.bashrc > "{{ home }}/.bashrc"

  - name: Add ble.sh to bashrc
    shell: echo "[[ \$- == *i* ]] && source ~/.config/ble.sh/out/ble.sh --noattach" | cat - "{{ home }}/.bashrc" > "{{ home }}/.temp" && mv "{{ home }}/.temp" "{{ home }}/.bashrc"

  - name: Add shebang to bashrc
    shell: echo "#!/usr/bin/env bash" | cat - "{{ home }}/.bashrc" > "{{ home }}/.temp" && mv "{{ home }}/.temp" "{{ home }}/.bashrc"
