  - name: Install Ble Dependencies
    become: true
    apt:
        pkg:
        - gawk
        - fzf

  - name: Check if fzf exists
    stat:
      path: "{{ XDG_CONFIG_HOME }}/.fzf"
    register: fzf_exists
    
  - name: Clone fzf
    become: true
    shell: git clone --depth 1 https://github.com/junegunn/fzf.git "{{ XDG_CONFIG_HOME }}/.fzf"
    when: not fzf_exists.stat.exists

  - name: Install fzf
    become: true
    shell: "{{ XDG_CONFIG_HOME }}/.fzf/install"

  - name: Check if ble.sh exists
    stat:
      path: "{{ XDG_CONFIG_HOME }}/ble.sh"
    register: blesh_exists
    
  - name: Clone ble.sh
    become: true
    shell: git clone --recursive https://github.com/akinomyoga/ble.sh.git "{{ XDG_CONFIG_HOME }}/ble.sh"
    when: not blesh_exists.stat.exists

  - name: Install ble.sh
    become: true
    shell: make -C "{{ XDG_CONFIG_HOME }}/ble.sh" install DESTDIR="{{ XDG_CONFIG_HOME }}/ble.sh" PREFIX=/usr/local
    
  - name: Add ble.sh config to skel
    become: true
    shell: cat config/bash/.blerc >> "/etc/skel/.skelrc"
