  - name: Install C Packages
    become: true
    apt:
        name: [
            clang,
            clang-tidy,
            gcc,
            g++,
            gdb,
            strace,
            valgrind
        ]

  - name: Install C PIP Packages
    become: true
    pip:
        name: [
            pyyaml,
            cpplint
        ]
