  - name: Install C Packages
    become: true
    apt:
        pkg:
        - clang
        - clang-tidy
        - gcc
        - g++
        - gdb
        - strace
        - valgrind

  - name: Install C PIP Packages
    become: true
    pip:
        pkg:
        - pyyaml
        - cpplint
