  - name: Download Chrome
    shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o "{{ home }}/google-chrome-stable_current_amd64.deb"

  - name: Install Chrome
    become: true
    shell: apt install "{{ home }}/google-chrome-stable_current_amd64.deb"

  - name: Run Chrome
    shell: google-chrome &

  - name: Kill Chrome
    become: true
    shell: pkill google-chrome
