  - name: Add google repo
    become: true
    deb822_repository:
      name: google
      types: deb
      uris: http://dl.google.com/linux/chrome/deb
      architectures: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
      suites: stable
      components: main
      signed_by: https://dl.google.com/linux/linux_signing_key.pub
      state: present
      enabled: true

  - name: Update apt
    become: true
    shell: apt update

  - name: Install chrome
    become: true
    apt:
        pkg:
        - chrome-gnome-shell
        - google-chrome-stable
        
  - name: Run Chrome
    shell: google-chrome &

  - name: Kill Chrome
    become: true
    shell: sleep 1 && pkill chrome || true
