  - name: Download Chrome
    shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: Install Chrome
    become: true
    shell: dpkg -i google-chrome-stable_current_amd64.deb

  - name: Run Chrome
    shell: Chrome &

  - name: Kill Chrome
    become: true
    shell: pkill chrome
