  - name: Install General Utilities
    become: true
    apt:
        pkg:
        - apt-utils
        - apt-file
        - make
        - cmake
        - git
        - build-essential
        - bash-completion
        - ca-certificates
        - command-not-found
        - gnome-shell
        - gnome-shell-extensions
        - xclip
        - tree
        - htop
        - iotop
        - gdm3
        - redis-tools
        - lm-sensors
        - landscape-common
        state: latest
        update_cache: true

  - name: Create xdg home
    shell: mkdir -p "{{item}}"
    loop:
      - "{{XDG_HOME}}"
      - "{{XDG_BIN_HOME}}"
      - "{{XDG_DATA_HOME}}"
      - "{{XDG_STATE_HOME}}"
      - "{{XDG_CACHE_HOME}}"
      - "{{XDG_CONFIG_HOME}}"
    
  - name: Add include to bashrc
    become: true
    shell: echo "source /etc/skel/.skelrc" >> "/etc/skel/.bashrc"
    
  - name: Add shebang to skel
    become: true
    shell: echo "#!/usr/bin/env bash" > "/etc/skel/.skelrc"

  - name: Add xdg settings to skel
    become: true
    shell: echo "export {{item.key}}={{item.value}}" >> "/etc/skel/.skelrc"
    with_items:
      - { key: "XDG_HOME", value: "$HOME" }
      - { key: "XDG_BIN_HOME", value: "{{XDG_BIN_HOME}}" }
      - { key: "XDG_DATA_HOME", value: "{{XDG_DATA_HOME}}" }
      - { key: "XDG_STATE_HOME", value: "{{XDG_STATE_HOME}}" }
      - { key: "XDG_CACHE_HOME", value: "{{XDG_CACHE_HOME}}" }
      - { key: "XDG_CONFIG_HOME", value: "{{XDG_CONFIG_HOME}}" }

  - name: Add config settings to skel
    become: true
    shell: cat config/bash/config.txt >> "/etc/skel/.skelrc"
        
  - name: Add bashrc to skel
    become: true
    shell: cat config/bash/.bashrc >> "/etc/skel/.skelrc"