  - name: Debug Common Start
    debug:
      msg: "Starting Common"
    when: common.start is defined
    
  - name: Debug Common End
    debug:
      msg: "Finished Common"
    when: common.end is defined
  
  - name: Install General Utilities
    become: true
    register: common.start
    apt:
        name: [
            apt-utils,
            apt-file,
            build-essential,
            ca-certificates,
            clang,
            clang-tidy,
            cmake,
            command-not-found,
            curl,
            gcc,
            g++,
            gdb,
            htop,
            nasm,
            make,
            openssh-client,
            pycodestyle,
            pydocstyle,
            pylint,
            python3,
            python3-pip,
            strace,
            valgrind,
            wget,
            wireshark,
            xclip
        ]

  - name: Install Python Packages
    become: true
    pip:
        name: [
            pyyaml,
            Mako,
            xmltodict,
            junit-xml,
            requests,
            python-gitlab,
            pylint,
            bcrypt,
            pyopenssl,
            cryptography ,
            pydocstyle,
            pycodestyle,
            cpplint
        ]

  - name: Clone cunity
    shell: git clone https://gitlab.com/cunity/cunit.git "{{ home }}/cunit"

  - name: Build cunity
    become: true
    register: common.end
    shell: "cd {{ home }}/cunit && cmake -H. -Bbuild && cmake --build build && cmake --install build"

