  - name: Install General Utilities
    become: true
    apt:
        pkg:
        - apt-utils
        - apt-file
        - build-essential
        - bash-completion
        - ca-certificates
        - cmake
        - command-not-found
        - curl
        - gnome-shell-extensions
        - chrome-gnome-shell
        - fzf
        - make
        - openssh-client
        - wget
        - xclip

  - name: Update Apt
    become: true
    shell: apt update

  - name: Setup config directory
    shell: mkdir -p "{{ home }}/.config"

  - name: Add config settings to bashrc
    shell: cat config/bash/config.txt > "{{ home }}/.bashrc"
