  - name: Install General Utilities
    become: true
    apt:
        name: [
            apt-utils,
            apt-file,
            build-essential,
            ca-certificates,
            cmake,
            command-not-found,
            curl,
            htop,
            nasm,
            make,
            openssh-client,
            wget,
            wireshark,
            xclip
        ]

  - name: Update Apt
    become: true
    shell: apt update

  - name: Setup config directory
    shell: mkdir -p "{{ home }}/.config"
