  - name: Install prereqs
    become: true
    apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

  - name: Add docker repo
    become: true
    deb822_repository:
      name: docker
      types: deb
      uris: https://download.docker.com/linux/ubuntu
      architectures: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
      suites: jammy
      components: stable
      signed_by: https://download.docker.com/linux/ubuntu/gpg
      state: present
      enabled: true

  - name: Update apt
    become: true
    shell: apt update

  - name: Install docker
    become: true
    apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  - name: Add docker group
    become: true
    shell: groupadd docker || true

  - name: Add to docker group
    become: true
    shell: usermod -aG docker {{ item }}
    loop:
      - "{{ user }}"
      - "{{ current_user }}"
      - "$USER"

  - name: Apply group
    become: true
    shell: newgrp docker

  - name: Start services
    become: true
    systemd:
      service: "{{item}}"
      enabled: yes
      state: started
    loop:
      - docker
