  - name: Install Firefox
    become: true
    apt:
        name: firefox

  - name: Run Firefox
    shell: firefox --headless &

  - name: Kill Firefox
    become: true
    shell: sleep 1 && pkill firefox
