  - name: Remove Snap Firefox
    become: true
    shell: snap remove firefox --purge || true

  - name: Update mozilla repo
    become: true
    apt_repository:
        repo: ppa:mozillateam/ppa

  - name: Prioritize APT Firefox
    become: true
    shell: cat config/apt/firefox_pref.txt >> /etc/apt/preferences.d/mozilla-firefox

  - name: Auto Update Firefox
    become: true
    shell: cat config/apt/firefox_upgd.txt >> /etc/apt/apt.conf.d/51unattended-upgrades-firefox

  - name: Install Firefox
    become: true
    apt:
        pkg:
        - firefox-esr

  - name: Run Firefox
    shell: firefox --headless &

  - name: Kill Firefox
    become: true
    shell: sleep 1 && pkill firefox || true
