  - name: Update golang repo
    become: true
    apt_repository:
        repo: ppa:longsleep/golang-backports

  - name: Install Golang
    become: true
    apt:
        pkg:
        - golang

  - name: Setup go bin
    become: true
    shell: echo 'export PATH=$PATH:/home/$USER/go/bin' >> /etc/skel/.bashrc

  - name: Install go packages
    shell: go install {{item}}
    loop:
      - github.com/go-task/task/v3/cmd/task@latest