  - name: Install prereqs
    become: true
    apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

  - name: Download keyring
    become: true
    shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: keyring permissions
    become: true
    shell: chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Add apt source
    become: true
    shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

  - name: source permissions
    become: true
    shell: chmod 644 /etc/apt/sources.list.d/kubernetes.list

  - name: Update apt
    become: true
    shell: apt update

  - name: Install kubectl
    become: true
    apt:
        pkg:
        - kubectl

  - name: Install k9s
    shell: go install github.com/derailed/k9s@latest

  - name: Setup k9s config
    shell: mkdir -p {{XDG_DATA_HOME}}/k9s

  - name: Write k9s hotkeys
    shell: cat config/kubernetes/k9s.txt >> {{XDG_DATA_HOME}}/k9s/hotkeys.yml
