  - name: Install micro
    become: true
    shell: curl https://getmic.ro | bash && mv ./micro /usr/bin/

  - name: Setup micro directory
    become: true
    shell: mkdir -p "{{ XDG_CONFIG_HOME }}/micro/plug/filemanager"

  - name: Install key bindings
    become: true
    shell: cp config/micro/bindings.json "{{ XDG_CONFIG_HOME }}/micro/"

  - name: Setup micro plugins
    shell: micro -plugin install filemanager jump quoter go manipulator wc lsp detectindent

  - name: Override default filemanager
    become: true
    shell:  curl https://raw.githubusercontent.com/Kyrasuum/filemanager-plugin/master/filemanager.lua > "{{ XDG_CONFIG_HOME }}/micro/plug/filemanager/filemanager.lua"

  - name: Install colorscheme
    become: true
    shell: mkdir -p "{{ XDG_CONFIG_HOME }}/micro/colorschemes" && cp config/micro/sublime.micro "{{ XDG_CONFIG_HOME }}/micro/colorschemes/"

  - name: Install syntax
    become: true
    shell: mkdir -p "{{ XDG_CONFIG_HOME }}/micro/syntax" && cp config/micro/glsl.yaml "{{ XDG_CONFIG_HOME }}/micro/syntax/" && cp config/micro/haxe.yaml "{{ XDG_CONFIG_HOME }}/micro/syntax/" && cp config/micro/vue.yaml "{{ XDG_CONFIG_HOME }}/micro/syntax/"

  - name: Set default git editor
    become: true
    shell: git config --global core.editor micro

  - name: Set default kube editor
    become: true
    shell: echo "export KUBE_EDITOR=micro" >> /etc/skel/.bashrc