  - name: Install minikube
    become: true
    shell: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

  - name: Start minikube
    shell: minikube start --driver=docker

  - name: Add docker context
    become: true
    shell: docker context create minikube --description "Minikube" --docker "host=tcp://192.168.49.2:2376,ca=/home/{{ home }}/.minikube/certs/ca.pem,cert=/home/{{ home }}/.minikube/certs/cert.pem,key=/home/{{ home }}/.minikube/certs/key.pem"
