  - name: Install nodejs and npm
    become: true
    apt:
        pkg:
        - nodejs
        - npm

  - name: Install Typescript
    become: true
    npm:
        name: typescript
        global: yes
