  - name: Install Python Packages
    become: true
    apt:
        name: [
            pycodestyle,
            pydocstyle,
            pylint,
            python3,
            python3-pip,
            python3-dbg
        ]

  - name: Install Python PIP Packages
    become: true
    pip:
        name: [
            pyyaml,
            Mako,
            xmltodict,
            junit-xml,
            requests,
            python-gitlab,
            pylint,
            bcrypt,
            pyopenssl,
            cryptography,
            pydocstyle,
            pycodestyle,
        ]
