  - name: Install Tilix
    become: true
    apt:
        pkg:
        - tilix
        - libvte-2.91-0
        - libvte-2.91-common

  - name: Set tilix config
    shell: dconf load /com/gexperts/Tilix/ < config/tilix/config
