  - name: Install Tilix
    become: true
    apt:
        name: [
            tilix,
            libvte-2.91-0,
            libvte-2.91-common
        ]

  - name: Set tilix config
    shell: dconf load /com/gexperts/Tilix/ < "{{ home }}/.config/tilix/config"

  - name: Add tilix to bashrc
    shell: echo "if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
    fi" | cat - "{{ home }}/.bashrc" > "{{ home }}/.temp" && mv "{{ home }}/.temp" "{{ home }}/.bashrc"
