  - name: get list of existing users
    getent:
      database: passwd

  - name: get list of existing usernames
    set_fact:
      existing_users: "{{ ansible_facts.getent_passwd.keys() | list }}"

  - name: Setup User
    become: true
    shell: useradd -p {{password}} -m -G sudo {{user}}
    when: current_user != user and user not in existing_users