  - name: Install VM Utilities
    become: true
    apt:
        pkg:
        - open-vm-tools
        - open-vm-tools-desktop
        state: latest
        update_cache: true
        
  - name: Start services
    become: true
    systemd:
      service: "{{item}}"
      enabled: yes
      state: started
    loop:
      - vmtoolsd

  - name: Switch from tty to GNOME
    become: true
    systemd:
      service: "gdm3"
      enabled: yes
      state: started
    when: ansible_architecture == 'aarch64'

  - name: Default to GNOME instead of tty
    become: true
    shell: systemctl set-default graphical.target
    when: ansible_architecture == 'aarch64'
 
  - name: Disable unneeded services
    become: true
    ansible.builtin.systemd:
      state: stopped
      name: "{{item}}"
      enabled: no
      masked: yes
    loop:
      - multipathd
      
  - name: Apply sysctl settings
    become: true
    sysctl: name={{item.key}} value={{item.value}}
    with_items:
      - { key: "vm.max_map_count", value: "262144" }
      - { key: "fs.inotify.max_user_instances", value: "256" }
      
  - name: Setup shared folder
    become: true
    shell: if grep -q "/vagrant" /etc/fstab; then true; else echo "\n#Vagrant Shared Folder\n.host:/vagrant /vagrant fuse.vmhgfs-fuse defaults,allow_other,uid=1000,gid=1000 0 0" >> /etc/fstab; fi
    
  - name: Setup hgfs
    become: true
    shell: cp config/vm/mnt-hgfs.mount /etc/systemd/system/
    
  - name: vm tools folders
    become: true
    shell: echo "fuse" >> /etc/modules-load.d/open-vm-tools.conf
    
  - name: enable hgfs service
    become: true
    shell: systemctl enable mnt-hgfs.mount
    
  - name: start hgfs service
    become: true
    shell: systemctl start mnt-hgfs.mount